# Generated by Django 3.1.4 on 2021-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="id",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="id",
        ),
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
