# Generated by Django 3.1.4 on 2021-04-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20210406_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
